Flow of control
JV-33/codelex-exercise pull request #4
Opened 2023-08-01 05:32 UTC by JV-33

Šoreiz būtu jābūt kā ar pirmo PR bez .gitignor! 
Ja viss ir kārtībā tad sapratu kur bija kļūda pie iepriekšējā faila !

2023-08-01 14:28 UTC, ausmoons requested changes

2023-08-01 14:28 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/Calculator/Calculator.csproj
> +
Ir par daudz failu

2023-08-02 12:45 UTC, JV-33 commented on csharp-basics/exercises/FlowOfControl/Calculator/Calculator.csproj
> +
Vai iespējams uzzinat, kuri ir lieki ?

2023-08-02 19:45 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/Calculator/Calculator.csproj
> +
![image](https://github.com/JV-33/codelex-exercise/assets/53189160/465869b2-72fe-47f8-803f-6f470c148459)

![image](https://github.com/JV-33/codelex-exercise/assets/53189160/6c36288a-a023-4f86-85f2-4369a435022c)

Taisot gitignore, izmantojot generatoru, tiek pateikts, ka bin, obj, . DS mapes un faili ir lieki. https://www.toptal.com/developers/gitignore/api/visualstudio,macos

2023-08-07 19:02 UTC, ausmoons requested changes

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/Calculator/Program.cs
> +            switch (darbiba)
Labāk kodu būtu rakstīt angliski. Tas priekš nākamajiem PR

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/LargestNumber/Program.cs
> +
Liekas tukšas rindas nekur nevajag atstāt

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/PhoneKeyPad/Program.cs
> +        Console.WriteLine($"Iznākums {result}");
Pēc } jauna tukša rinda

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/PhoneKeyPad/Program.cs
> +
Liekas tukšas rindas

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/PhoneKeyPad/Program.cs
> +        }
Pēc }, ja seko kods, parasti vajag tukšu rindu

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/PrintDayInWord/Program.cs
> +
Pietiek ar vienu tukšu rindu

2023-08-07 19:02 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/TenBillion/Program.cs
> +
Pietiek ar vienu tukšu rindu

2023-08-09 12:47 UTC, JV-33 commented on csharp-basics/exercises/FlowOfControl/Calculator/Program.cs
> +            switch (darbiba)
Labi . Kaut kā pieradums muļķigs ! Sākšu No klasēm un objektiem

2023-08-09 19:01 UTC, ausmoons approved these changes

2023-08-11 16:01 UTC, merged