Loops
JV-33/codelex-exercise pull request #6
Opened 2023-08-09 12:37 UTC by JV-33

2023-08-09 18:59 UTC, ausmoons requested changes

2023-08-09 18:59 UTC, ausmoons commented on csharp-basics/exercises/Loops/Exercise 10/obj/project.assets.json
> +  "targets": {
Atkal lieki faili. Pirms taisa commit, ir jāpaskatās, ko commito

2023-08-11 16:07 UTC, EdgarsSalmins commented on csharp-basics/exercises/Loops/Exercise 10/obj/project.assets.json
> +  "targets": {
salabojām.

2023-08-11 16:07 UTC, EdgarsSalmins approved these changes

2023-08-11 16:07 UTC, merged