aClasses and objects
JV-33/codelex-exercise pull request #7
Opened 2023-08-18 14:01 UTC by JV-33

2023-08-19 08:40 UTC, EdgarsSalmins commented on csharp-basics/exercises/Collections/DaysNames/Program.cs
> +            foreach (DayOfWeek day in Enum.GetValues(typeof(DayOfWeek)))
virziens labs bet tas pats ar linq jāizdara bija. :)

2023-08-19 08:40 UTC, EdgarsSalmins commented on csharp-basics/exercises/Collections/DecrypNumber/Program.cs
> +            foreach (var item in cryptedNumbers)
šis arī bija linq uzdevums. :)

2023-08-19 08:45 UTC, EdgarsSalmins requested changes
daži sīkumi.

2023-08-20 06:16 UTC, ausmoons commented on csharp-basics/exercises/Collections/.gitignore
> +# Windows image file caches
Lieki faili iekš PR

2023-08-20 06:17 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise 10/Program.cs
> +
Liekas tukšas rindas

2023-08-20 06:23 UTC, ausmoons commented on csharp-basics/exercises/Collections/UniquValues/Program.cs
> +            var uniqueString = values.Distinct().ToArray();
Nesanāk kā piemērā  //ToDo: Given a non-empty list of strings, return a list that contains only unique (non-duplicate) strings.
            //ToDo: Example: ["abc", "xyz", "klm", "xyz", "abc", "abc", "rst"] → ["klm", "rst"]

2023-08-22 13:55 UTC, JV-33 commented on csharp-basics/exercises/Collections/.gitignore
> +# Windows image file caches
man pat bija .gitignore ar  # Ignore the `bin` and `obj` directories
**/bin/
**/obj/

# Ignore .DS_Store files (specifically for macOS)
.DS_Store 

Bet tāpat aizgāja.

2023-08-23 18:47 UTC, ausmoons requested changes

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/DecryptNumber/Program.cs
> +
Liekas tukšas rindas

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/Exercise 4/Program.cs
> +        }
Pēc } jauna tukša rinda, ja seko kods

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/.gitignore
> +
Tu var fiziski izdzēst failus no šī brancha iekš github, tad vajadzētu failiem pazust

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/Histogram/Program.cs
> +       {
Sakārto failu, { vajadz dziļāk

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/ListExercise7/Program.cs
> +                if (item == "White")
bez loop šis ir jāpaveic (.Contains())

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/NumberFromRange/Program.cs
> +            }
} pēc tukša rinda, ja seko kods

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/NumberFromRange/Program.cs
> +
Liekas tukšas rindas

2023-08-23 18:47 UTC, ausmoons commented on csharp-basics/exercises/Collections/UniquValues/Program.cs
> +            var uniqueString = values.Distinct().ToArray();
.

2023-08-24 07:37 UTC, JV-33 commented on csharp-basics/exercises/Collections/NumberFromRange/Program.cs
> +
man ar šo kodu izprintē tikai unikālos 
Meow
Hello
Hi!
Bye

2023-08-25 15:56 UTC, ausmoons commented on csharp-basics/exercises/Collections/NumberFromRange/Program.cs
> +
piemērā rāda, ka bija jāizprintē tikai tie, kuri bija 1 reizi. Tātad hi un Meow neder

2023-08-27 17:08 UTC, JV-33 commented
negribēju merge !!! netīšam uzspiedu

2023-08-29 16:41 UTC, ausmoons requested changes
Salabo UniqueValues, pārējais ir ok

2023-08-29 16:41 UTC, ausmoons commented on csharp-basics/exercises/Collections/UniquValues/Program.cs
> +            var uniqueString = values.Distinct().ToArray();
Te neder distinct

2023-08-30 19:40 UTC, ausmoons requested changes

2023-08-30 19:40 UTC, ausmoons commented on csharp-basics/exercises/Collections/UniquValues/Program.cs
>              {
![image](https://github.com/JV-33/codelex-exercise/assets/53189160/6d847d0e-b89c-402b-ae52-844c325ff6fd)
 šāds rezultāts neder. Hi un Meow ir minēti 2 reizes iekš values

2023-08-31 14:04 UTC, JV-33 commented on csharp-basics/exercises/Collections/UniquValues/Program.cs
>              {
Un es kaut kā visu laiku  domājis un sapratis ka unikālās vajag tādā ziņā kad izprintējam tikai kā unikāli vienu ! Vienkārši ārprāts ar mani   ;(

2023-09-07 16:32 UTC, ausmoons approved these changes

2023-09-07 16:33 UTC, ausmoons commented on csharp-basics/exercises/Collections/UniquValues/Program.cs
>              {
Es arī neaizdomātos, ja chatā par šo nebūtu viens jautājis.

2023-09-07 16:53 UTC, merged